### ISSUE TITLE
Jako gość/użytkownik/administrator/schronisko po ekranie powitalnym chcę zobaczyć listę zwierząt posortowaną od najnowszych, żeby od razu widzieć ostatnio dodane profile zwierząt.

### ISSUE THREAD

**Issue by purpleturtll** [purpleturtll/inzynierka#2]

**Comment by purpleturtll** [comment]
- [x] #20 Implementacja widoku listy w aplikacji klienta
- [x] #21 Implementacja paginacji profili na serwerze

**Comment by michal-kapala** [comment]
@bartoszCzarnecki pisałeś już sortowanie po dacie na serwerze? Myślę że będzie łatwiej ale na kliencie też da się zrobić, bez pośpiechu though, baza danych/podstawowe API to priorytety na teraz
