### ISSUE TITLE
Środowisko deweloperskie do rozwoju i testów aplikacji mobilnej

### ISSUE THREAD

**Issue by michal-kapala** [purpleturtll/inzynierka#24]
Instalacja i konfiguracja:
1. IDE - [Visual Studio Code](https://code.visualstudio.com/)
2. Środowisko do wirtualizacji - [Android Studio](https://developer.android.com/studio)
3. Środowisko uruchomieniowego aplikacji - [ExpoCLI](https://docs.expo.io/)
4. Środowisko uruchomieniowego React Native - [Node.js](https://nodejs.org/en/)
5. Projekt aplikacji (React Native)

**Comment by purpleturtll** [comment]
Można by sprawdzić czy samo AVD wystarczy. Wtedy można by zainstalować samo Android SDK zamiast całego Android Studio. Ale to taki off topic.
