### ISSUE TITLE
Jako użytkownik chcę mieć możliwość dodawania i usuwania profili zwierząt z mojego prywatnego, lokalnego podzbioru zwierząt (listy obserwowanych zwierząt), żeby nie musieć wyszukiwać ich profili w globalnej liście zwierząt.  

### ISSUE THREAD

**Issue by purpleturtll** [purpleturtll/inzynierka#3]

**Comment by michal-kapala** [comment]
Aktualnie na branchu `state_mgmt` mamy globalny stan dla listy zwierzaków który można zmieniać przez kliknięcie serduszka na karcie zwierzaka (_favourite/not favourite_), jest jednak problem z renderingiem kart - te same karty są na dwóch różnych screenach (_Home_, _Favourites_) i w tej chwili nie ma synchronizacji między nimi, tj. kliknięcie i zmiana stanu jest widoczna tylko na ekranie, z którego jest wykonana. Stan globalny zmienia się poprawnie (zgodnie z kliknięciami), więc zostawiłbym to na razie tak jak jest, jak dopniemy komunikację klient-serwer możemy pomyśleć o rozwiązaniu tego (np. hook `useEffect` rerenderujący komponent karty/screen na zmianę stanu globalnego).
