### ISSUE TITLE
Jako gość/użytkownik chcę mieć możliwość łatwego wyszukiwania zwierząt o interesujących mnie cechach wybierając je (cechy) spośród dostępnych filtrów (m.in. wiek, płeć, rasa, kolor sierści czy miejsce przebywania zwierzęcia). 

### ISSUE THREAD

**Issue by purpleturtll** [purpleturtll/inzynierka#4]

**Comment by annaciszak** [comment]
Filtry:
- [ ] typ (zwierzęcia)
- [ ] płeć
- [ ] lokalizacja
- [ ] statusy: do adopcji, dom tymczasowy, pilne, kwarantanna
- [ ] wiek
- [ ] waga
- [ ] w typie rasy

**Comment by michal-kapala** [comment]
State management dla filtrów dla mnie na ten tydzień (14.10 - 21.10), kopnijcie mnie w tyłek jeśli nie zrobię
